<b><h1>Data Types and Operators</h1></b>
<h4>Welcome to this lesson on Data Types and Operators! You'll learn about:
</h4>

* **Data Types:** Integers, Floats, Booleans, 
Strings, Lists, Tuples, Sets, Dictionaries

* **Operators:** Arithmetic, Assignment, Comparison, Logical, Membership, Identity

* Built-In Functions, Compound Data Structures, Type Conversion

* Whitespace and Style Guidelines

<br><br>

<h2><b>1. Print() function in python:</b></h2>

You will be seeing this print function very frequently in python programming. It helps us to see what exactly is happening in our code.

Try to run the next lines of code and see what happens next:

In [ ]:
2+7
2*7

* You will see that even though you had written 2 lines of code only the last line of code gets seen in the output area.

Now this happens because you haven't told python what to alctually do with it.

This is where *print()* comes in. *print()* in python is a useful builtin function that we can use to display input value as text in the output.

In [ ]:
print(2+7)
print(2*7)

In [ ]:
print('Hello World!!!!')

<br><br>

## **4. Variables:**<br>
Understanding variables is very important in any programming language they are used all the time in python. Using variables in place of direct numbers have many advantages. Variables are used to store information to be referenced and manipulated in a computer program.

Creating a new variable in python is very simple, lets create one together, here in this example below the variable name is *month*, the equal sign is the assignment operator and the value of the variable is 12.

In [ ]:
month=12
print(month)

Now its your turn create a variable named *rent* with its value being 1700

In [ ]:
# create and print the varibale rent down below

##### Expected output:<br>1700

In any case, whatever term is on the left side, is now a name for whatever value is on the right side. Once a value has been assigned to a variable name, you can access the value from the variable name.

For example if we run this code we will get 3 as the output here as in the first line we assigned 3 to *a* and in the second line we assigned *a* to *b* so when we print *b* we get 3 as the output.

In [ ]:
a=3
b=a
print(b)

If we don't declare the variable and try to print the output then we will get the following error

In [ ]:
print(x)

<br><br>

## **5. Multiple Assignment Operator:**

Suppose you are making a program where in you enter the dimensions of the tank and it will give the volume of the tank as the output. So you can write code as:

In [ ]:
height = 3
length = 6
width = 2
volume = height * length * width
print(volume)

Now python has a very useful way to assign multiple variables together in a single line using multiple assignment like this:

In [ ]:
# this will now assign 3 to height, 6 to length and 2 to width just as before.
height , length , width = 3 , 6 , 2
volume = height * length * width
print(volume)

<br><br>

## **6. Variable Naming Conventions:**

There are some rules we need to follow while giving a name for a Python variable.

- **Rule-1**: You should start variable name with an alphabet or **underscore(_)** character.
- **Rule-2:** A variable name can only contain **A-Z,a-z,0-9** and **underscore(_)**.
- **Rule-3:** You cannot start the variable name with a **number**.
- **Rule-4:** You cannot use special characters with the variable name such as such as **$,%,#,&,@.-,^** etc.
- **Rule-5**: Variable names are **case sensitive**. For example str and Str are two different variables.
- **Rule-6:** Do not use reserve keyword as a variable name for example keywords like **class, for, def, del, is, else,** **try, from,** etc. more examples are given below and as we go through the course we will come across many more. Creating names that are descriptive of the values often will help you avoid using any of these words.

In [ ]:
#Allowed variable names

x=2
y="Hello"
mypython="PythonGuides"
my_python="PythonGuides"
_my_python="PythonGuides"
_mypython="PythonGuides"
MYPYTHON="PythonGuides"
myPython="PythonGuides"
myPython7="PythonGuides"

In [ ]:
#Variable name not Allowed

7mypython="PythonGuides"
-mypython="PythonGuides"
myPy@thon="PythonGuides"
my Python="PythonGuides"
for="PythonGuides"

#It shows invalid syntax. 
#It will execute one by one and will show the error.

Also there are some naming convention that needs to be followed like:

* try to keep the name of the variables descriptive short but descriptive.    **for example:** when taking inputs for the height of a tree of a box the appropriate  variable name will be just *height* not *x* not *h* not *height_of_the_tree*.

* Also the pythonic way to name variables is to use all lowercase letters and underscores to separate words.

In [ ]:
# pythonic way

my_height = 58
my_lat = 40
my_long = 105

In [ ]:
# not pythonic way
my height = 58 # wont work
MYLONG = 40    # will work still avoid using it
MyLat = 105    # will work still avoid using it

Though the last two of these would work in python, they are not pythonic ways to name variables. The way we name variables is called snake case, because we tend to connect the words with underscores.



What if we want to change or update the value of a variable for example take the example of rent = 1700, suppose the rent has hiked and the new rent is 2000 we can just assign the variable its new value as:

In [ ]:
rent = 1700
rent = 2000
print(rent)

This is called overwriting the variable , i.e, When a new value is assigned to a variable, the old one is forgotten.

If we had then caused some damages to the property during our crazy house party and we have to pay for them then we can just apply these changes directly to this variable.

In [ ]:
rent = 1700
rent = 2000
rent =rent + 700
print(rent)

in the line 3 the variable *rent* is being assigned to itself plus 700 which results to 2700. 

Because such increment and assignment operations are very common python has a very special assignment operator for this.

In [ ]:
rent = 1700
rent = 2000
rent += 700
print(rent)

we can actually use this **+=** operator to tell python that we are incrementing the value on the left by the value on the right. **+=** is a example of assignment operator **-= *= /=** are some more examples of assignment operators. All of these operators just apply arithmetic operation to the variable on the left with the value on the right which makes your code more concise and easier to read and understand.

<br><br>

## **7. Integers and Floats:**
So far the numbers that we have dealt with were mostly whole numbers or integers, but as you may have notices that other types of numbers also do exist. For example dividing one integer by another gives us a number that isn't an integer, in python we represent such a number as a float, which is short for floating point number.

In [ ]:
print(3/2)

Numbers with a decimal point, such as 3.14, are called floating-point numbers (or floats). Note that even though the value 42 is an integer, the value 42.0 would be a floating-point number. And if 2 integers are divided then also we get float as an answer.

You can check the datatype of any value by using the builtin function of type, that returns the type of an object. Here as you can see they type of a number without a decimal and the type of a number with a decimal.

In [ ]:
a = 3
b = 2.5

print(type(a))
print(type(b))

An operation involving an int and a float will always give float as its output. We can also covert one datatype to another by constructing new objects of those types with int and float. 

When we convert a float to an int the part after the decimal point is dropped and hence there is no rounding. eg 28.9 will be cut to 28. 

Similarly converting int to float just adds a decimal at the end of the number and a 0 after that. example 3 will become 3.0

In [ ]:
a = float(3)
b = int(28.9)
print(a)
print(b)



> Another point that you need to keep in mind is float are an approximation to the number they represent. As float can represent very large range of numbers python must use approximation to represent these numbers. For example this floating point number 0.23 is in reality slightly more than 0.23. such that if we add up 0.23 to itself a few times and check its equality to the expected resultant it will be different. Although the difference is very small but it exists never the less and you should know about it.

In [ ]:
print(0.23 + 0.23 + 0.23 + 0.23 + 0.23 + 0.23
       + 0.23 + 0.23 + 0.23 + 0.23 + 0.23 + 0.23
       + 0.23 + 0.23 + 0.23 + 0.23 + 0.23 + 0.23
       + 0.23 + 0.23 + 0.23 + 0.23 + 0.23 + 0.23
       + 0.23 + 0.23 + 0.23 + 0.23+ 0.23 + 0.23 == 6.9)

<br><br>

##**9. Boolean Datatype, Comparison and Logical Operators:**

Bool is another datatype that is commonly used in Python. Bool is short for Boolean which can have a value of either True or False. Boolean algebra is the branch of algebra in which the values of the variables are the truth values true or false. Boolean algebra us the framework on which all electronic devices and built and exists fundamentally in every line of code inside a computer. In python we can easily assign boolean values like this:

In [ ]:
python_awsome = True
doumentation_bad = False

We can use comparison operators to compare 2 values and produce boolean results like:

In [ ]:
a = 3 > 1
print(a)

Here 3 is greater than 1 so printing out the output gives us a boolean value to true. There are many comparison operators in python, as you can see here are all of them.

As you will see the function of all these comparison operators are evident from their names itself these are **less than,  greater than , less than or equal to, greater than or equal to, not equal to**.

Working with boolean has its own set of operators called as logical operators. These operators very useful when working with boolean, and evaluates if both the sides are true, **OR** evaluates if atleast one side is true and **not** evaluates the inverse of the input boolean.

Lets understand if via an example:

In [ ]:
rent = 1200
is_affordable = rent > 1000 and rent < 2000

print(is_affordable)

Here we check if the *rent* of a house is affordable or not, here in the second line we evaluate both the sides ie *rent > 1000*, yes, so it is **true** while the second condition is *rent < 200*, that too is **true**. as both the condition on the left and right side of and is **true** hence the boolean value of **true** will be assigned to the *is_affordable variable*. In other words if the *rent* is greater than 1000 and less than 2000 then only it is affordable.

And here you can see how not works:

In [ ]:
rent = 1200
is_affordable = not(rent > 1000 and rent < 2000) #"not" just inverts bool value

print(is_affordable)

<br><br>

## **10. Strings:**

Python has another datatype in its toolkit called as Strings, as the name suggest this datatype deals with characters words and text. String is a immutable order of sequences of characters (eg, Letters, numbers, spaces and symbols. We will be explaining what does immutable order means later on.

You can create a string by using quotes as seen here, you can use either single / double quotes they both work equally well but there are some cases where you might prefer one over the other which we will be discussing below.

In [ ]:
# using Double Quotes
print("ShapeAI")
# using Single Quotes
print('ShapeAI')

In this example we printed the word *ShapeAI* using single and double quotes and got the same output *ShapeAI*.

We can also assign a string to a variable just like float and int.

In [ ]:
motto = "Learn | Code | Compete | Intern" 
print(motto)

Strings in Python are shown as the variable type str.

In [ ]:
type(motto)

> *String can contain any character number symbol space within the quotes.
However if we want to have quotes inside the string we get an error.*

In [ ]:
dialogue = "shiva said, "you learn as you grow""

Python provides 2 easy ways to handle such problem:

1. Place the string in single quotes rather than double quotes. This will solve your problem for having double quotes within the string. But sometimes you will want to have both double and single quotes in your string in that case this will prove to be a problem.

In [ ]:
dialogue = 'shiva said, "you learn as you grow"'
print(dialogue)

2. In that case we can use a backslash to skip quotes as you can see in this example. The backslash helps python to know that the the single quote should be interpreted as part of the string rather than the quote that ends the string.

In [ ]:
dialogue = '"shiva you\'re bag is red"'
print(dialogue)

There are a few operators that we use on floats and ints that can also be used on strings. For example we can use the **'+'** to combine / concatenate 2 strings together and we can use **'*'** to repeat the string let us look at an example for each.

In [ ]:
print("hello" + "world")

print("hello" + " " + "world")

> *here in this example we can see that using the plus arithmetic operator we get *helloworld* written together but this word that is printed out has no meaning, we need to have a space between both the words to have a meaning. We can add another string containing just a space in between the words to do so.*

In [ ]:
word = "hello"
print(word * 5)

Now in the second example we can see that using the multiplication operator on a string we get repetition of the same word as many time as the number we multiplied the string by in the output.

However unlike multiplication and addition operators the other arithmetic operators like division and subtraction cannot be used on strings any attempt to do so would result in an error that string is an unsupported datatype for the division/subtraction operator.

In [ ]:
word_1 = "hello"
word_2 = "world"
print(word_1 / word_2)

A useful builtin function for string datatypes is *len()* which stands for length. As the name suggests (it returns the length of an object ie., it returns the no of characters in a string.

It takes in values in a parenthesis and returns the length of the string. *len()* is a little different from *print()* as the value returned from length can be stored in a variable as seen in the example here. The *len()* function outputs a value 7 that is then stored in a variable called as *word_length* which is then printed out.

In [ ]:
word_length = len("ShapeAI")
print(word_length)

### **Question:**

The line of code in the following code block will cause a *SyntaxError*, thanks to the misuse of quotation marks. First run it with Test Run to view the error message. Then resolve the problem so that the quote (from Mahatama Gandhi) is correctly assigned to the variable *gandhi_quote*.

In [ ]:
# TODO: Fix this string!
gandhi_quote = 'If you don't ask, you don't get it'

### **Question:**

In this question you have to print the accuracy logs of a model in training.

In [ ]:
model = "VGG16"
iteration = "150"
accuracy = "67.98"

# TODO: print a log message using the variables above
# This message should have the same format as this one:
# "the accuracy of ResNET50 model in 100th iteration is: 42.16%"

### **Question:**

Use string concatination and *len()* function to fing the length of a persons complete name and store it in the variable *name_length*.

As a business card designer find if the name can fit into a business card.

In [ ]:
given_name = "Rahul"
middle_names = "Shastri"
family_name = "Mishra"

name_length = #todo: calculate how long this name is

# Now we check to make sure that the name fits within the driving license character limit
# Nothing you need to do here
driving_license_character_limit = 28
print(name_length <= driving_license_character_limit)